name: nearby_discovery
description: Test
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter_reactive_ble: ^5.0.3

dependency_overrides:
  flutter_reactive_ble:
    path: ../flutter_reactive_ble

